- name: Prepare a Yocto build enviroment
  hosts: yocto_builders
  become: true
  vars:
#  connection: local
    vol_size: 4 # GB or 4 * (1024^3) bytes
    image_dir: "/var/images"
    file_path: "sdcard.img"
    image_path: "{{ image_dir }}/{{ file_path }}"
    partitions:
      - number: 1
        start: "1MB"
        end: "100MB"
        fs_type: "fat32"
      - number: 2
        start: "100MB"
        end: "100%"
        fs_type: "ext4"

  tasks:
    - name: Create a place for disk volumes
      file:
        path: "{{ image_dir }}"
        state: directory
        recurse: true
        
    - name: Create disk image file
      shell:
        cmd: "dd if=/dev/zero of={{ image_dir }}/{{ file_path }}  bs=1024  count=$((1024 * 1024 * {{ vol_size }} ))"
        creates: "{{ image_path }}"

    - name: Check if loopback is mounted
      shell:
        cmd: "losetup --list --json"
      register: loopback_check
      tags: loopback

    - name: Parse loopback output to json
      set_fact:
        loopback_json: "{{ loopback_check.stdout | from_json }}"
      tags: loopback

    #
    # check that the new file has been loopback mounted 
    #
    - name: Create loopback on the file
      shell:
        cmd: "losetup --find --show --json  {{ image_path }}"
      when: image_path not in loopback_json.loopdevices | map(attribute='back-file') | list 
      tags: loopback
      register: loopback_create


    #
    # Create and Label Partitions and filesystems on loopback file
    #
    - name: "Add Partitions to loopback disk image"
      community.general.parted:
        device: /dev/loop0
        label: msdos
        number: "{{ item.number }}"
        part_type: primary
        unit: MB
        part_start: "{{ item.start }}"
        part_end: "{{ item.end }}"
        fs_type: "{{ item.fs_type }}"
        state: present
      loop: "{{ partitions }}"
      when: loopback_create.changed is true
      tags: partition
      register: parted

    - name: Create VFAT FS on partition 1
      shell:
        cmd: "mkfs.vfat /dev/loop0p1 -n BOOT"
      when: parted.changed is true

    - name: Create ext4 FS on partition 2
      shell:
        cmd: "mkfs.ext4 /dev/loop0p2 -L ROOT"
      when: parted.changed is true
